FROM nodered/node-red:3.0.2

#
# Add node modules for Node-RED
#   https://nodered.org/docs/getting-started/docker
#
RUN \
    npm install \
    node-red-contrib-letsfiware-ngsi \
    node-red-contrib-web-worldmap
